### ISSUE TITLE
Add MDEDITOR_CONFIGS to setting.py error

### ISSUE THREAD

**Issue by leo493852107** [pylixm/django-mdeditor#13]
Hi pylixm, thanks for sharing, great project! I have one question and one suggestion, could you pls help?

- When I add MDEDITOR_CONFIGS to setting.py, it raise error, how to solve it? (Python 3.6 & Django 2.0.7)

```
Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x10c3875c0>
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 589, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/urls/resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/leo/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/leo/Documents/WorkSpace/Python/hey_star/hey_star/urls.py", line 62, in <module>
    url(r'mdeditor/', include('mdeditor.urls')),
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/leo/.pyenv/versions/3.6.5/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/mdeditor/urls.py", line 4, in <module>
    from .views import UploadView
  File "/Users/leo/.pyenv/versions/hey_star/lib/python3.6/site-packages/mdeditor/views.py", line 14, in <module>
    MDEDITOR_CONFIGS = settings.MDEDITOR_CONFIGS['default'] if hasattr(settings, 'MDEDITOR_CONFIGS') else DEFAULT_CONFIG
KeyError: 'default'
```

- When I want to show image in html, it show Markdown in html, could you pls provide more detail for other developers?
And I solve by this Article [支持 Markdown 语法和代码高亮](https://www.zmrenwu.com/post/11/)

### Anyway, thanks .

**Comment by pylixm** [comment]
1. when adding settings to the MDEDITOR_CONFIGS parameter, you must have a nested dictionary with default key, which is reserved for later support for multiple edit boxes with different configurations. Sorry, this local document is misleading, I have modified the document. Thank you for pointing out.

2.  You can see this example: [show content in html ](https://github.com/pylixm/django-mdeditor/blob/master/mdeditor_demo_app/templates/show.html).
